import type { ArticleCard } from '~/types/api'

/**
 * Returns the static mock article dataset used when the backend is unavailable.
 * Replace this with a real API call (useArticleFilter → useApi) once backend is live.
 */
export const useMockArticles = (): ArticleCard[] => [
  {
    article_id: '1',
    article_title: 'Review Samsung Galaxy S25 Ultra: Flagship Terbaik 2025?',
    article_preview: 'Kami menguji Galaxy S25 Ultra selama dua minggu penuh. Hasilnya mengejutkan dari sisi kamera, performa gaming, dan daya tahan baterai harian.',
    article_tags: ['smartphone', 'samsung', 'flagship'],
    article_image: null,
    rating_avg: 4.5,
    comment_count: 24,
    created_at: '2025-03-15',
  },
  {
    article_id: '2',
    article_title: 'ASUS ROG Zephyrus G16 2025: Laptop Gaming Tipis Bertenaga',
    article_preview: 'ROG Zephyrus G16 hadir dengan Ryzen AI 9 HX dan RTX 5080 dalam chassis setebal 18mm. Layak beli untuk gamer serius?',
    article_tags: ['laptop', 'gaming', 'asus'],
    article_image: null,
    rating_avg: 4.2,
    comment_count: 18,
    created_at: '2025-03-10',
  },
  {
    article_id: '3',
    article_title: 'Sony WH-1000XM6: Raja ANC Tetap Berdiri Kokoh',
    article_preview: 'Generasi keenam headphone flagship Sony ini membawa peningkatan signifikan pada noise cancellation adaptif dan kualitas suara Hi-Res.',
    article_tags: ['audio', 'sony', 'headphone'],
    article_image: null,
    rating_avg: 4.8,
    comment_count: 41,
    created_at: '2025-02-28',
  },
  {
    article_id: '4',
    article_title: 'MacBook Air M4: Ultrabook Terbaik untuk Produktivitas?',
    article_preview: 'Apple memperbarui MacBook Air dengan chip M4. Performa melonjak drastis, tapi apakah worth the upgrade dari pengguna M3?',
    article_tags: ['laptop', 'apple', 'ultrabook'],
    article_image: null,
    rating_avg: 4.6,
    comment_count: 37,
    created_at: '2025-02-20',
  },
  {
    article_id: '5',
    article_title: 'LG OLED C5 65": Layar Terbaik untuk Ruang Tamu',
    article_preview: 'LG OLED C5 menghadirkan panel WOLED generasi baru dengan kecerahan puncak 3000 nit. Kami ukur semuanya secara objektif.',
    article_tags: ['display', 'tv', 'oled'],
    article_image: null,
    rating_avg: 4.7,
    comment_count: 29,
    created_at: '2025-02-14',
  },
  {
    article_id: '6',
    article_title: 'Xiaomi 15 Ultra: Kamera Leica Makin Matang di 2025',
    article_preview: 'Kolaborasi Xiaomi dan Leica kini sampai iterasi ketiganya. Kualitas foto dan video mengalami peningkatan besar yang terasa nyata.',
    article_tags: ['smartphone', 'xiaomi', 'kamera'],
    article_image: null,
    rating_avg: 4.3,
    comment_count: 15,
    created_at: '2025-02-05',
  },
  {
    article_id: '7',
    article_title: 'Intel Core Ultra 9 285K vs Ryzen 9 9950X: Battle 2025',
    article_preview: 'Dua prosesor desktop paling kencang saat ini diadu head-to-head — gaming, rendering, encoding video, dan efisiensi daya.',
    article_tags: ['processor', 'intel', 'amd'],
    article_image: null,
    rating_avg: 4.4,
    comment_count: 52,
    created_at: '2025-01-28',
  },
  {
    article_id: '8',
    article_title: 'Anker Soundcore Liberty 4 Pro: TWS Budget Rasa Premium',
    article_preview: 'Di harga di bawah satu juta, Anker menawarkan ANC, LDAC, dan form factor nyaman seharian. Benarkah sebagus klaimnya?',
    article_tags: ['audio', 'tws', 'budget'],
    article_image: null,
    rating_avg: 4.1,
    comment_count: 8,
    created_at: '2025-01-20',
  },
  {
    article_id: '9',
    article_title: 'Logitech MX Master 4S: Mouse Produktivitas Terbaik?',
    article_preview: 'MX Master 4S hadir dengan sensor baru 8000 DPI, wheel MagSpeed generasi kedua, dan konektivitas Bluetooth yang lebih stabil.',
    article_tags: ['aksesoris', 'logitech', 'produktivitas'],
    article_image: null,
    rating_avg: 4.6,
    comment_count: 33,
    created_at: '2025-01-12',
  },
]
